wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.12
    start_time: 1709897400.774381
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.14.0
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
random_seed:
  desc: null
  value: 42
